// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ungdztzywifsioyyadcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZ2R6dHp5d2lmc2lveXlhZGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTMwOTMsImV4cCI6MjA1ODcyOTA5M30.16qrxX9ta-mRLjCa0kSp6bmjeL0EX3Pbg-kM_jsmEtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);